# Generated by Django 4.2.3 on 2023-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ordered', models.CharField(max_length=32)),
                ('requested_time', models.DateTimeField()),
                ('reason', models.CharField(max_length=32)),
                ('approval', models.BooleanField()),
            ],
        ),
    ]
