# Generated by Django 4.2.3 on 2023-07-10 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('delivery', '0001_initial'),
        ('product_cart', '0002_product_cart_products'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=32)),
                ('order_date', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=32)),
                ('contact_number', models.CharField(max_length=32)),
                ('payment_status', models.BooleanField()),
                ('order_status', models.BooleanField()),
                ('payment_method', models.CharField(max_length=32)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('delivery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('product_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_cart.product_cart')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
