# Generated by Django 4.2.3 on 2023-07-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_product_vendor'),
        ('product_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cart',
            name='products',
            field=models.ManyToManyField(to='inventories.product'),
        ),
    ]
