# Generated by Django 4.2.2 on 2023-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Id', models.IntegerField()),
                ('Order_Date', models.DateTimeField()),
                ('Order_Status', models.CharField(max_length=32)),
                ('Order_Total', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
